name: Debug Netlify
on:
  workflow_dispatch:

jobs:

  deploy_to_netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy _redirects file to build
        run: |
          cp -v _redirects build/
          echo "Verifying _redirects file in build directory:"
          cat build/_redirects

      - name: Publish
        id: netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --json --prod --dir ./build --message "production [${{ github.sha }}]"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
